import * as grpc from '@grpc/grpc-js';
import { ServiceDefinition, EnumTypeDefinition, MessageTypeDefinition } from '@grpc/proto-loader';

import { PublishBuildEventClient as _google_devtools_build_v1_PublishBuildEventClient } from './google/devtools/build/v1/PublishBuildEvent';

type ConstructorArguments<Constructor> = Constructor extends new (...args: infer Args) => any ? Args: never;
type SubtypeConstructor<Constructor, Subtype> = {
  new(...args: ConstructorArguments<Constructor>): Subtype;
}

export interface ProtoGrpcType {
  google: {
    api: {
      CustomHttpPattern: MessageTypeDefinition
      Http: MessageTypeDefinition
      HttpRule: MessageTypeDefinition
    }
    devtools: {
      build: {
        v1: {
          BuildEvent: MessageTypeDefinition
          BuildStatus: MessageTypeDefinition
          ConsoleOutputStream: EnumTypeDefinition
          OrderedBuildEvent: MessageTypeDefinition
          /**
           * A service for publishing BuildEvents. BuildEvents are generated by Build
           * Systems to record actions taken during a Build. Events occur in streams,
           * are identified by a StreamId, and ordered by sequence number in a stream.
           * 
           * A Build may contain several streams of BuildEvents, depending on the systems
           * that are involved in the Build. Some BuildEvents are used to declare the
           * beginning and end of major portions of a Build; these are called
           * LifecycleEvents, and are used (for example) to indicate the beginning or end
           * of a Build, and the beginning or end of an Invocation attempt (there can be
           * more than 1 Invocation in a Build if, for example, a failure occurs somewhere
           * and it needs to be retried).
           * 
           * Other, build-tool events represent actions taken by the Build tool, such as
           * target objects produced via compilation, tests run, et cetera. There could be
           * more than one build tool stream for an invocation attempt of a build.
           */
          PublishBuildEvent: SubtypeConstructor<typeof grpc.Client, _google_devtools_build_v1_PublishBuildEventClient> & { service: ServiceDefinition }
          PublishBuildToolEventStreamRequest: MessageTypeDefinition
          PublishBuildToolEventStreamResponse: MessageTypeDefinition
          PublishLifecycleEventRequest: MessageTypeDefinition
          StreamId: MessageTypeDefinition
        }
      }
    }
    protobuf: {
      Any: MessageTypeDefinition
      DescriptorProto: MessageTypeDefinition
      Duration: MessageTypeDefinition
      Empty: MessageTypeDefinition
      EnumDescriptorProto: MessageTypeDefinition
      EnumOptions: MessageTypeDefinition
      EnumValueDescriptorProto: MessageTypeDefinition
      EnumValueOptions: MessageTypeDefinition
      FieldDescriptorProto: MessageTypeDefinition
      FieldOptions: MessageTypeDefinition
      FileDescriptorProto: MessageTypeDefinition
      FileDescriptorSet: MessageTypeDefinition
      FileOptions: MessageTypeDefinition
      GeneratedCodeInfo: MessageTypeDefinition
      MessageOptions: MessageTypeDefinition
      MethodDescriptorProto: MessageTypeDefinition
      MethodOptions: MessageTypeDefinition
      OneofDescriptorProto: MessageTypeDefinition
      OneofOptions: MessageTypeDefinition
      ServiceDescriptorProto: MessageTypeDefinition
      ServiceOptions: MessageTypeDefinition
      SourceCodeInfo: MessageTypeDefinition
      Timestamp: MessageTypeDefinition
      UninterpretedOption: MessageTypeDefinition
    }
  }
}

